ALTER TABLE discounts ADD COLUMN IF NOT EXISTS minimum_member_tier VARCHAR(20) NOT NULL DEFAULT 'V_STAR';
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS customer_segment VARCHAR(20) NOT NULL DEFAULT 'ALL';
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS applicable_movie_ids TEXT;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS applicable_genres TEXT;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS applicable_theater_ids TEXT;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS applicable_room_ids TEXT;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS applicable_showtime_ids TEXT;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS applicable_channels VARCHAR(100) NOT NULL DEFAULT 'CINEMA';
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS applicable_weekdays VARCHAR(100);
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS start_hour TIME;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS end_hour TIME;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS per_user_limit INTEGER NOT NULL DEFAULT 1;
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS budget_limit NUMERIC(14,2);
ALTER TABLE discounts ADD COLUMN IF NOT EXISTS budget_used NUMERIC(14,2) NOT NULL DEFAULT 0;

ALTER TABLE payments ADD COLUMN IF NOT EXISTS discount_id UUID;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS discount_code VARCHAR(50);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS original_amount NUMERIC(12,2);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS discount_amount NUMERIC(12,2) NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_payment_discount ON payments(discount_id, status);
