INSERT INTO movies (
    id,
    title,
    description,
    duration_minutes,
    rating,
    active,
    poster_url,
    director,
    actors,
    genre,
    release_date,
    language,
    rated,
    status
)
VALUES
    (
        'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
        'Avengers: Endgame',
        'The Avengers assemble one last time to reverse Thanos'' snap and restore the universe.',
        181,
        8.40,
        TRUE,
        'https://example.com/posters/avengers-endgame.jpg',
        'Anthony Russo, Joe Russo',
        'Robert Downey Jr., Chris Evans, Scarlett Johansson',
        'Action, Adventure, Sci-Fi',
        '2019-04-26',
        'English',
        'PG-13',
        'NOW_SHOWING'
    ),
    (
        'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
        'Inside Out 2',
        'Riley enters her teen years and new emotions arrive inside headquarters.',
        96,
        7.90,
        TRUE,
        'https://example.com/posters/inside-out-2.jpg',
        'Kelsey Mann',
        'Amy Poehler, Maya Hawke, Kensington Tallman',
        'Animation, Adventure, Comedy',
        '2024-06-14',
        'English',
        'PG',
        'NOW_SHOWING'
    ),
    (
        'cccccccc-cccc-cccc-cccc-cccccccccccc',
        'Dune: Part Two',
        'Paul Atreides joins the Fremen and rises against the forces occupying Arrakis.',
        166,
        8.70,
        TRUE,
        'https://example.com/posters/dune-part-two.jpg',
        'Denis Villeneuve',
        'Timothee Chalamet, Zendaya, Rebecca Ferguson',
        'Epic, Sci-Fi, Drama',
        '2024-03-01',
        'English',
        'PG-13',
        'COMING_SOON'
    ),
    (
        '550e8400-e29b-41d4-a716-446655440001',
        'Avengers: Secret Wars',
        'Cuộc chiến cuối cùng của các siêu anh hùng xuyên đa vũ trụ.',
        180,
        8.90,
        TRUE,
        'https://example.com/posters/secret-wars.jpg',
        'Anthony Russo',
        'Tom Holland, Benedict Cumberbatch',
        'Action, Sci-Fi',
        '2026-12-18',
        'English',
        'PG-13',
        'COMING_SOON'
    ),
    (
        '550e8400-e29b-41d4-a716-446655440002',
        'Lật Mặt 9',
        'Bí mật được hé lộ sau nhiều năm che giấu.',
        125,
        8.20,
        TRUE,
        'https://example.com/posters/latmat9.jpg',
        'Lý Hải',
        'Huy Khánh, Quách Ngọc Tuyên',
        'Action, Drama',
        '2026-04-30',
        'Vietnamese',
        'T16',
        'NOW_SHOWING'
    ),
    (
        '550e8400-e29b-41d4-a716-446655440003',
        'Dune: Messiah',
        'Paul Atreides tiếp tục hành trình thống trị thiên hà.',
        165,
        8.70,
        TRUE,
        'https://example.com/posters/dune-messiah.jpg',
        'Denis Villeneuve',
        'Timothée Chalamet, Zendaya',
        'Sci-Fi, Adventure',
        '2026-11-20',
        'English',
        'PG-13',
        'COMING_SOON'
    ),
    (
        '550e8400-e29b-41d4-a716-446655440004',
        'Conan Movie 2026',
        'Vụ án bí ẩn nhất mà Conan từng đối mặt.',
        110,
        8.40,
        TRUE,
        'https://example.com/posters/conan2026.jpg',
        'Yuzuru Tachikawa',
        'Minami Takayama',
        'Animation, Mystery',
        '2026-05-01',
        'Japanese',
        'PG',
        'NOW_SHOWING'
    ),
    (
        '550e8400-e29b-41d4-a716-446655440005',
        'Spider-Man: Beyond the Spider-Verse',
        'Miles Morales khám phá những chiều không gian mới.',
        140,
        9.10,
        TRUE,
        'https://example.com/posters/spiderverse.jpg',
        'Joaquim Dos Santos',
        'Shameik Moore, Hailee Steinfeld',
        'Animation, Action',
        '2026-08-14',
        'English',
        'PG',
        'COMING_SOON'
    )
ON CONFLICT (title) DO NOTHING;
