# Server
server.port=8080

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ThauFilmmm
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.baseline-version=0

# JWT
jwt.secret=FilmTicketSecretKey2024VeryLongSecretKeyForHS512AlgorithmAtLeast64BytesLong
jwt.access-expiration=3600000
jwt.refresh-expiration=2592000000

# Google OAuth
spring.security.oauth2.client.registration.google.client-id=429243335491-scnfecbtd48ihe0khob2i9ekqgvfv90f.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# CORS
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173