ALTER TABLE movies
    ADD COLUMN IF NOT EXISTS poster_url VARCHAR(500),
    ADD COLUMN IF NOT EXISTS director VARCHAR(255),
    ADD COLUMN IF NOT EXISTS actors TEXT,
    ADD COLUMN IF NOT EXISTS genre VARCHAR(255),
    ADD COLUMN IF NOT EXISTS release_date DATE,
    ADD COLUMN IF NOT EXISTS language VARCHAR(100),
    ADD COLUMN IF NOT EXISTS rated VARCHAR(50);

ALTER TABLE movies
    ADD COLUMN IF NOT EXISTS status VARCHAR(20);

UPDATE movies
SET status = COALESCE(status, 'COMING_SOON');

ALTER TABLE movies
    ALTER COLUMN status SET DEFAULT 'COMING_SOON';

ALTER TABLE movies
    ALTER COLUMN status SET NOT NULL;

ALTER TABLE movies
    DROP CONSTRAINT IF EXISTS movies_status_check;

ALTER TABLE movies
    ADD CONSTRAINT movies_status_check CHECK (status IN ('NOW_SHOWING', 'COMING_SOON'));
